name: "Build fishcrow flavor of NixOS on Ubuntu latest"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - run: nix shell nixpkgs#nixos-build -c nixos-build build --flake .#fishcrow
