---
name: "Lint nix flakes on Ubuntu latest"

on:
  pull_request:
    branches:
      - main
      - dev
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install zsh
      run: sudo apt-get update; sudo apt-get install zsh
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        github_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - run: nix shell nixpkgs#alejandra -c alejandra "$(find . -name \"**/*.nix\")"
      shell: zsh {0}
